---
abstract: 'use F<libasyncns> for C<IO::Async> resolver queries'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  Test::More: '0.88'
dynamic_config: 1
generated_by: 'Module::Build version 0.4204, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: IO-Async-Resolver-LibAsyncNS
provides:
  IO::Async::Resolver::LibAsyncNS:
    file: lib/IO/Async/Resolver/LibAsyncNS.pm
    version: '0.01'
requires:
  Future: '0'
  IO::Async::Handle: '0'
  IO::Async::Resolver: '0'
  Net::LibAsyncNS: '0'
resources:
  license: http://dev.perl.org/licenses/
version: '0.01'
